//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazek.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public int Bet_id { get; set; }
        public Nullable<int> Sesion_id { get; set; }
        public Nullable<int> BetAmount { get; set; }
        public string betResult { get; set; }
    
        public virtual Sesion Sesion { get; set; }
    }
}
