//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazek.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pofile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pofile()
        {
            this.Sesion = new HashSet<Sesion>();
            this.Transact_history = new HashSet<Transact_history>();
        }
    
        public int Prof_id { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> balance { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesion> Sesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transact_history> Transact_history { get; set; }
    }
}
